title: CS 416 Narrative Visualization
description: A narrative visualization project using D3.js and the Cayman theme
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
plugins:
  - jekyll-theme-cayman
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
highlighter: rouge
relative_links:
  enabled: true
  collections: true
